version: "3.8"

services:
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true

    environment:
      - MYSQL_DATABASE=nodeDb
      - MYSQL_ROOT_PASSWORD=root


    ports:
      - "3306:3306"

