/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.biblioteca_reges.views;

import br.com.biblioteca_reges.dominios.Aluno;
import br.com.biblioteca_reges.dominios.Endereco;
import br.com.biblioteca_reges.rdn.AlunoRdn;
import br.com.biblioteca_reges.rdn.EnderecoRdn;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class FrmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCliente
     */
    int id = 0;
    boolean modoAlterarDeletar = false;

    public FrmCliente() {
        initComponents();
        this.habilitarCampos(false);

        this.modoInicial();
        //this.carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAluno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRaAluno = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAluno = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRg = new javax.swing.JTextField();
        txtNascimento = new javax.swing.JFormattedTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 6, 165, -1));

        jLabel2.setText("Documento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 147, -1));

        jLabel3.setText("Idade");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel4.setText("Senha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 20));
        getContentPane().add(txtRaAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 80, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 77, 161, -1));

        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 80, -1, -1));

        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 114, -1, -1));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 111, 161, -1));

        jLabel11.setText("Bairro");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 182, -1, -1));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 179, 161, -1));

        tableAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Documento", "Telefone", "Nascimento", "E-mail", "Fidelidade", "Rua", "Bairro", "Cep", "Cidade", "Número"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAluno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 207, 736, 195));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 408, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 408, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 408, -1, -1));
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 145, 161, -1));

        jLabel10.setText("Rua");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 148, -1, -1));

        jLabel13.setText("Número");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 145, 83, -1));

        jLabel14.setText("Cidade");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 148, -1, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 145, 83, -1));

        lblUf.setText("Uf");
        getContentPane().add(lblUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 148, -1, -1));
        getContentPane().add(txtUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 145, 83, -1));

        jLabel15.setText("Cep");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 182, -1, -1));
        getContentPane().add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 179, 83, -1));

        jLabel8.setText("Rg");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 40, -1, -1));
        getContentPane().add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 40, 165, -1));

        txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        getContentPane().add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 92, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 408, -1, -1));

        jLabel6.setText("Nascimento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 20));
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 130, -1));

        jLabel9.setText("Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Calendar cal = Calendar.getInstance();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {

            cal.setTime(sdf.parse(txtNascimento.getText()));
        } catch (ParseException ex) {
            throw new RuntimeException("Erro ao converter a data. Certifique-se de inserir a data no formato correto (dd/MM/yyyy).", ex);
        }

        //int id, String logradouro, String bairro, String numero, String cidade, String uf, String cep, int idAluno) {
        //carregar os objetos
        Endereco endereco = new Endereco(0, txtRua.getText(),
                txtBairro.getText(), txtNumero.getText(),
                txtCidade.getText(), txtUf.getText(), txtCep.getText(), this.id);

        Aluno aluno = new Aluno(this.id,
                Integer.parseInt(txtRaAluno.getText()),
                txtSenha.getText(),
                txtAluno.getText(),
                endereco,
                txtTelefone.getText(),
                cal,
                txtDocumento.getText(),
                txtRg.getText(),
                txtEmail.getText()
        );

        aluno.imprimir();

          AlunoRdn rdn = new AlunoRdn();
        if(this.modoAlterarDeletar == true){
        
            rdn.alterarAluno(aluno);
        }
        else{
        //enviar para o banco de dados
      
        rdn.inserirAluno(aluno);
        }
        //limpar os componentes
        limparCampos();

        //modo inicial
        modoInicial();

        //desabilitar componentes
        habilitarCampos(false);
        
        this.carregarTabela();


    }//GEN-LAST:event_btnSalvarActionPerformed


    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        this.habilitarCampos(true);

        this.modoNovo();

    }//GEN-LAST:event_btnNovoActionPerformed

    private void tableAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlunoMouseClicked
        // TODO add your handling code here:
        this.modoAlterarDeletar = true;

        //PEGA A LINHA SELECIONADA
        int row = this.tableAluno.getSelectedRow();

        //RECUPERA O VALOr DA COLUNA ID ESTA NA 0
        int idAluno = (int) this.tableAluno.getValueAt(row, 0);

        //GUARDA O ID PARA ALTERAR/REMOVER
        this.id = idAluno;

        //int indice = 0;
        AlunoRdn rdn = new AlunoRdn();

        //RECUPERAR POR ID
        Aluno aluno = rdn.obterPorId(id);

      
        txtAluno.setText(aluno.getNomeCompleto());
        txtSenha.setText(aluno.getAlunoSenha());
        txtRg.setText(aluno.getRgIe());
        txtEmail.setText(aluno.getEmail());
        txtTelefone.setText(aluno.getTelefone());
        txtDocumento.setText(aluno.getDocumento());

        //ALTERAR A DATA
        DateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");
        txtNascimento.setText(formataData.format(aluno.getDataNascFund().getTime()));

        txtRua.setText(aluno.getEndereco().getLogradouro());
        txtNumero.setText(aluno.getEndereco().getNumero());
        txtBairro.setText(aluno.getEndereco().getBairro());
        txtCep.setText(aluno.getEndereco().getCep());

        txtUf.setText(aluno.getEndereco().getUf());
        txtCidade.setText(aluno.getEndereco().getCidade());

        this.habilitarCampos(true);

        btnNovo.setEnabled(false);

        btnExcluir.setEnabled(true);

        btnSalvar.setText("Alterar");
        
        btnSalvar.setEnabled(true);


    }//GEN-LAST:event_tableAlunoMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        int input = JOptionPane.showConfirmDialog(null,
                "Deseja realmente excluir?", "Atenção!!!", JOptionPane.YES_NO_OPTION);

        if (input == 0) {

            EnderecoRdn endRdn = new EnderecoRdn();

            endRdn.deletarEnderecoPorAluno(this.id);

            AlunoRdn rdn = new AlunoRdn();

            rdn.deletarAluno(this.id);

            this.carregarTabela();

        }
        this.modoNovo();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
            this.limparCampos();
            this.habilitarCampos(false);
            this.btnSalvar.setEnabled(false);
            this.btnExcluir.setEnabled(false);
            this.btnSalvar.setText("Salvar");
            this.btnNovo.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void modoInicial() {
        this.btnNovo.setEnabled(true);
        this.btnSalvar.setEnabled(false);
        this.btnExcluir.setEnabled(false);
    }

    private void modoNovo() {
        this.btnNovo.setEnabled(false);
        this.btnSalvar.setEnabled(true);
        this.btnExcluir.setEnabled(false);

        this.limparCampos();
        this.btnSalvar.setEnabled(true);
        this.btnSalvar.setText("Salvar");
    }

    private void limparCampos() {
        txtBairro.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtDocumento.setText("");
        txtEmail.setText("");
        txtRaAluno.setText("");
        txtNascimento.setText("");
        txtAluno.setText("");
        txtNumero.setText("");
        txtRg.setText("");
        txtSenha.setText("");
        txtRua.setText("");
        txtTelefone.setText("");
        txtUf.setText("");
    }

    private void habilitarCampos(boolean ativo) {
        txtBairro.setEnabled(ativo);
        txtSenha.setEnabled(ativo);
        txtCep.setEnabled(ativo);
        txtCidade.setEnabled(ativo);
        txtDocumento.setEnabled(ativo);
        txtEmail.setEnabled(ativo);
        txtRaAluno.setEnabled(ativo);
        txtNascimento.setEnabled(ativo);
        txtAluno.setEnabled(ativo);
        txtNumero.setEnabled(ativo);
        txtRg.setEnabled(ativo);
        txtRua.setEnabled(ativo);
        txtTelefone.setEnabled(ativo);
        txtUf.setEnabled(ativo);
    }

    private void carregarTabela() {

        //CLASSE USADA PARA MANIPULAR A TABELA
        DefaultTableModel model = (DefaultTableModel) tableAluno.getModel();

        //limpar a tabela antes de selecionar
        model.setRowCount(0);

        AlunoRdn cliRdn = new AlunoRdn();

        List<Aluno> lstCli = cliRdn.obterTodos();

        //para cada aluno da lista
        if (lstCli != null) {
            for (Aluno cli : lstCli) {

                DateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");

                //adicionar a linha
                model.addRow(new Object[]{
                    cli.getId(),
                    cli.getNomeCompleto(),
                    cli.getDocumento(),
                    cli.getTelefone(),
                    formataData.format(cli.getDataNascFund().getTime()),
                    cli.getEmail(),
                    cli.getEndereco().getLogradouro(),
                    cli.getEndereco().getBairro(),
                    cli.getEndereco().getCep(),
                    cli.getEndereco().getCidade(),
                    cli.getEndereco().getNumero(),
                    cli.getEndereco().getUf()
                });
            }
        }
        tableAluno.setModel(model);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUf;
    private javax.swing.JTable tableAluno;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtNascimento;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRaAluno;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables
}
