/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.biblioteca_reges.views;

import br.com.biblioteca_reges.dominios.Livro;
import br.com.biblioteca_reges.rdn.ConnectionFactory;
import br.com.biblioteca_reges.rdn.LivroRdn;
import java.awt.Image;
import java.text.ParseException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
/**
 *
 * @author doniz
 */
public class FrmLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmLivro
     */
    public FrmLivro() {
        initComponents();
        
        ImageIcon icon = new ImageIcon("Assets/lupa.png");
        Image originalImage = icon.getImage();
        Image resizedImage = originalImage.getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        
        ImageIcon resizedIcon = new ImageIcon(resizedImage);
        botPesquisaLivro.setIcon(resizedIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLivro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        cadLivro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botPesquisaLivro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        txtLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLivroActionPerformed(evt);
            }
        });
        getContentPane().add(txtLivro);
        txtLivro.setBounds(140, 80, 120, 25);

        jLabel2.setText("Autor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 122, 36, 19);
        getContentPane().add(txtAutor);
        txtAutor.setBounds(50, 150, 113, 25);

        jLabel3.setText("Preço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(279, 122, 38, 19);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco);
        txtPreco.setBounds(279, 150, 80, 25);

        jLabel4.setText("Categoria");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(181, 122, 64, 19);
        getContentPane().add(txtCategoria);
        txtCategoria.setBounds(181, 150, 80, 25);

        cadLivro.setText("Cadastrar");
        cadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadLivroActionPerformed(evt);
            }
        });
        getContentPane().add(cadLivro);
        cadLivro.setBounds(120, 260, 100, 25);

        jLabel5.setText("Cadastro de Materiais");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 10, 190, 40);

        botPesquisaLivro.setText("Pesquisar");
        botPesquisaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisaLivroActionPerformed(evt);
            }
        });
        getContentPane().add(botPesquisaLivro);
        botPesquisaLivro.setBounds(270, 80, 95, 25);

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 290, 90, 25);

        jLabel6.setText("Quantidade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 180, 76, 19);
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(50, 202, 49, 25);

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 260, 90, 25);

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 290, 88, 25);

        jLabel7.setText("Nome do produto");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 80, 130, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadLivroActionPerformed

        Calendar dataAtual = Calendar.getInstance();

        Livro livro = new Livro(txtLivro.getText(),
           txtAutor.getText(),
           Integer.parseInt(txtQuantidade.getText()),
           Float.parseFloat(txtPreco.getText()),
           txtCategoria.getText(),
           dataAtual
        );

        livro.imprimir();
        
        //enviar para o banco de dados
        LivroRdn rdn = new LivroRdn();
        
        rdn.cadastrarLivro(livro);
        
        //limpar os componentes
        limparCampos();
    }//GEN-LAST:event_cadLivroActionPerformed

    private void txtLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLivroActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void botPesquisaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisaLivroActionPerformed
        
        LivroRdn livro = new LivroRdn();
        
        Livro resultSearch = livro.obterLivroPorNome(txtLivro.getText());
        
        if(resultSearch == null){
            System.out.println("Livro não encontrado no banco!");
        };
        
        txtLivro.setText(resultSearch.getNomeLivro());
        txtAutor.setText(resultSearch.getNomeAutor());
        txtQuantidade.setText(String.valueOf(resultSearch.getQuantidade()));
        txtPreco.setText(String.valueOf(resultSearch.getPreco()));
        txtCategoria.setText(resultSearch.getCategoria());
    }//GEN-LAST:event_botPesquisaLivroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        LivroRdn livro = new LivroRdn();
        
        Livro livroModel = new Livro(txtLivro.getText(),
           txtAutor.getText(),
           Integer.parseInt(txtQuantidade.getText()),
           Float.parseFloat(txtPreco.getText()),
           txtCategoria.getText(),
           null
        );
        
        int livroId = livro.obterLivroIdPorNome(txtLivro.getText());
        boolean resultUpdate = livro.atualizarPorId(livroId, livroModel);
        
        if(resultUpdate){
            System.out.println("Livro Atualizado com sucesso!!");
        };
        
        limparCampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        LivroRdn livro = new LivroRdn();
        
        int livroId = livro.obterLivroIdPorNome(txtLivro.getText());
        boolean resultDelete = livro.deletarPorId(livroId);
        
        if(resultDelete){
            System.out.println("Livro deletado com sucesso!!");
        };
        
        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void limparCampos() {
        txtLivro.setText((""));
        txtAutor.setText("");
        txtQuantidade.setText("");
        txtCategoria.setText("");
        txtPreco.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botPesquisaLivro;
    private javax.swing.JButton cadLivro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtLivro;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
