/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.biblioteca_reges.views;

import br.com.biblioteca_reges.rdn.AlunoRdn;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author doniz
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JButton();
        txtSenha = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonEmp1 = new javax.swing.JButton();
        jLabel4ttt1 = new javax.swing.JLabel();
        jLabel4ttt2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuCadastro = new javax.swing.JMenu();
        Usuario = new javax.swing.JMenuItem();
        Livros = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPanel.setBackground(new java.awt.Color(204, 204, 204));

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cadastro");
        jLabel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));
        jInternalFrame1.getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 160, 213, -1));
        jInternalFrame1.getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 110, 213, -1));

        jLabel2.setText("Email");
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 82, -1, -1));

        jLabel3.setText("Senha");
        jInternalFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 138, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Bem vindo à ConstruReges");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Materiais de Construção");
        jInternalFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        ButtonEmp1.setText("Login");
        ButtonEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEmp1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(ButtonEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel4ttt1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4ttt1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4ttt1.setText("Cadastro");
        jLabel4ttt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4ttt1MouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jLabel4ttt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 30));

        jLabel4ttt2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4ttt2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4ttt2.setText("Cadastro");
        jLabel4ttt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4ttt2MouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jLabel4ttt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 30));

        desktopPanel.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPanelLayout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 221, Short.MAX_VALUE))
        );

        JMenuCadastro.setText("Cadastro");

        Usuario.setText("Usuário");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        JMenuCadastro.add(Usuario);

        Livros.setText("Materiais");
        Livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivrosActionPerformed(evt);
            }
        });
        JMenuCadastro.add(Livros);

        jMenuBar1.add(JMenuCadastro);

        exit.setText("Sair");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
       FrmCliente frmAluno = new FrmCliente();
        desktopPanel.add(frmAluno);
        frmAluno.setVisible(true);
    }//GEN-LAST:event_UsuarioActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void jLabel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel4ActionPerformed
        AlunoRdn aluno = new AlunoRdn();
        
        int verifyAluno = aluno.verificarPorEmailESenha(txtEmail.getText(), txtSenha.getText());
        System.out.println(verifyAluno);
        
    }//GEN-LAST:event_jLabel4ActionPerformed

    private void ButtonEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEmp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEmp1ActionPerformed

    private void jLabel4ttt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4ttt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4ttt1MouseClicked

    private void jLabel4ttt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4ttt2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4ttt2MouseClicked

    private void LivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivrosActionPerformed
        FrmMateriais frmLivro = new FrmMateriais();
        desktopPanel.add(frmLivro);
        frmLivro.setVisible(true);
    }//GEN-LAST:event_LivrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEmp1;
    private javax.swing.JMenu JMenuCadastro;
    private javax.swing.JMenuItem Livros;
    private javax.swing.JMenuItem Usuario;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JMenu exit;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLabel4;
    private javax.swing.JLabel jLabel4ttt1;
    private javax.swing.JLabel jLabel4ttt2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
